In [2]:
import pandas as pd
import numpy as np

user_items = pd.DataFrame(np.random.randint(0,10,size=(100, 3)), columns=['user_id', 'movie_id', 'rating'])

In [5]:
# Create user-by-item matrix
user_by_movie = user_items.groupby(['user_id', 'movie_id'])['rating'].max().unstack()

In [6]:
user_by_movie

movie_id    0    1    2    3    4    5    6    7    8    9
user_id
0         2.0  NaN  1.0  NaN  8.0  NaN  NaN  NaN  NaN  7.0
1         NaN  9.0  NaN  NaN  NaN  6.0  8.0  8.0  NaN  6.0
2         3.0  NaN  4.0  6.0  6.0  0.0  NaN  NaN  3.0  0.0
3         NaN  NaN  6.0  NaN  NaN  0.0  6.0  7.0  5.0  NaN
4         NaN  3.0  5.0  7.0  NaN  6.0  8.0  4.0  8.0  7.0
5         2.0  NaN  0.0  2.0  NaN  7.0  9.0  NaN  6.0  NaN
6         3.0  2.0  0.0  9.0  NaN  9.0  NaN  1.0  8.0  4.0
7         5.0  2.0  8.0  9.0  4.0  NaN  9.0  8.0  9.0  8.0
8         9.0  4.0  9.0  NaN  NaN  NaN  0.0  3.0  NaN  8.0
9         4.0  8.0  3.0  7.0  NaN  4.0  9.0  6.0  NaN  8.0

In [7]:
# an array of movies the user has watched
movies = user_by_movie.loc[user_id][user_by_movie.loc[user_id].isnull() == False].index.values

NameError: name 'user_id' is not defined

In [ ]:
# user movie dict
n_users = user_by_movie.shape[0]
movies_seen = dict()

cnter = 0
bar = progressbar.Progressbar(maxval=n_user+1), widgets=[progressbar.Bar('=', '[', ']'), ' ', progressbar.Percentage()])
bar.start()

for user1 in range(1, n_users+1):

    # assign list of movies to each user key
    movies_seen[user1] = movies_watched(user1)

    cnter+=1
    bar.update(cnter)

bar.finish()

In [ ]:
# Remove outliers
movies_to_analyze = dict()

for user, movies in movies_seen.items():
    if len(movies) > lower_bound:
        movies_to_analyze[user] = movies
            
movies1 = movies_to_analyze[user1]
movies2 = movies_to_analyze[user2]

sim_movs = np.intersect1d(movies1, movies2, assume_unique=True)


df = user_by_movie.loc[(user1, user2), sim_movs]
corr = df.transpose().corr().iloc[0,1]

In [ ]:
# Pull movies for each user
movies1 = movies_to_analyze[user1]
movies2 = movies_to_analyze[user2]

# Find Similar Movies
sim_movs = np.intersect1d(movies1, movies2, assume_unique=True)

# Calculate correlation between the users
df = user_by_movie.loc[(user1, user2), sim_movs]
corr = df.transpose().corr().iloc[0,1